name: Test

on:
  push:
    branches: [master]

jobs:
  test-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ~/.cache
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn ci
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
      - run: yarn semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
